import jsPDF from "jspdf";
import type { TripPlan, BudgetBreakdown } from "../types";

const BRAND_COLOR: [number, number, number] = [42, 157, 143];
const TEXT_DARK: [number, number, number] = [20, 20, 24];
const TEXT_MUTED: [number, number, number] = [100, 100, 110];

const addHeader = (doc: jsPDF, title: string) => {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 30, "F");
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("YatraSathi", 14, 14);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 23);
  doc.setTextColor(...TEXT_DARK);
};

const addFooter = (doc: jsPDF, pageNum: number) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`Generated by YatraSathi AI Travel Planner  •  Page ${pageNum}`, 14, pageHeight - 8);
};

export const exportTripPlanPDF = (plan: TripPlan): void => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 40;
  let page = 1;

  addHeader(doc, `Trip Plan: ${plan.destination}`);

  const checkPageBreak = (needed = 20) => {
    if (y + needed > 270) {
      addFooter(doc, page);
      doc.addPage();
      page++;
      addHeader(doc, `Trip Plan: ${plan.destination}`);
      y = 40;
    }
  };

  // Summary
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text("Trip Summary", 14, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`Duration: ${plan.duration} days  |  Style: ${plan.travelStyle}  |  Est. Cost: ₹${plan.totalEstimatedCost.toLocaleString()}`, 14, y);
  y += 10;

  // Itinerary
  for (const day of plan.itinerary) {
    checkPageBreak(30);

    doc.setFillColor(255, 245, 245);
    doc.roundedRect(12, y - 4, 185, 8, 2, 2, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_COLOR);
    doc.text(`Day ${day.day}: ${day.theme}`, 14, y + 1);
    y += 10;

    for (const act of day.activities) {
      checkPageBreak(14);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...TEXT_DARK);
      doc.text(`${act.time}  ${act.name}`, 16, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...TEXT_MUTED);
      const lines = doc.splitTextToSize(act.description, 170);
      doc.text(lines as string[], 16, y);
      y += (lines as string[]).length * 4 + 2;
    }

    y += 4;
  }

  // Tips
  if (plan.tips.length) {
    checkPageBreak(20);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEXT_DARK);
    doc.text("Pro Tips", 14, y);
    y += 7;

    for (const tip of plan.tips) {
      checkPageBreak(10);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...TEXT_MUTED);
      const lines = doc.splitTextToSize(`• ${tip}`, 180);
      doc.text(lines as string[], 14, y);
      y += (lines as string[]).length * 4 + 2;
    }
  }

  addFooter(doc, page);
  doc.save(`YatraSathi_${plan.destination.replace(/\s+/g, "_")}_Trip.pdf`);
};

export const exportBudgetPDF = (budget: BudgetBreakdown): void => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let page = 1;

  addHeader(doc, `Budget Estimate: ${budget.destination}`);

  let y = 44;

  const checkPageBreak = (needed = 20) => {
    if (y + needed > 270) {
      addFooter(doc, page);
      doc.addPage();
      page++;
      addHeader(doc, `Budget Estimate: ${budget.destination}`);
      y = 44;
    }
  };

  // Meta line
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);
  doc.text(
    `${budget.days} days  |  ${budget.travelers} traveler(s)  |  ${budget.travelStyle}  |  Currency: ${budget.currency ?? "INR"}`,
    14,
    y
  );
  y += 12;

  // Summary
  if (budget.summary) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bolditalic");
    doc.setTextColor(...TEXT_DARK);
    const summaryLines = doc.splitTextToSize(budget.summary, 180);
    doc.text(summaryLines as string[], 14, y);
    y += (summaryLines as string[]).length * 5 + 8;
  }

  // Breakdown header
  checkPageBreak(16);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text("Cost Breakdown", 14, y);
  y += 10;

  const rows: [string, string, number][] = [
    ["Accommodation", `INR ${budget.accommodation.toLocaleString()}`, budget.accommodation],
    ["Food & Dining", `INR ${budget.food.toLocaleString()}`, budget.food],
    ["Transport", `INR ${budget.transport.toLocaleString()}`, budget.transport],
    ["Activities & Sightseeing", `INR ${budget.activities.toLocaleString()}`, budget.activities],
    ["Shopping", `INR ${budget.shopping.toLocaleString()}`, budget.shopping],
    ["Miscellaneous", `INR ${budget.miscellaneous.toLocaleString()}`, budget.miscellaneous],
  ];
  const subTotal = rows.reduce((s, r) => s + r[2], 0);

  for (const [label, value] of rows) {
    checkPageBreak(12);
    doc.setFillColor(248, 248, 252);
    doc.roundedRect(12, y - 4, 185, 10, 2, 2, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT_DARK);
    doc.text(label, 16, y + 2);
    doc.setFont("helvetica", "bold");
    doc.text(value, 190, y + 2, { align: "right" });
    y += 12;
  }

  // Total row
  checkPageBreak(16);
  doc.setFillColor(...BRAND_COLOR);
  doc.roundedRect(12, y, 185, 13, 3, 3, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("TOTAL ESTIMATED BUDGET", 16, y + 9);
  doc.text(`INR ${budget.total.toLocaleString()}`, 190, y + 9, { align: "right" });
  y += 20;

  // Per-person / per-day
  checkPageBreak(14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);
  doc.text(
    `Per Person: INR ${budget.perPersonTotal?.toLocaleString() ?? Math.round(budget.total / budget.travelers).toLocaleString()}   |   Per Day: INR ${budget.perDayTotal?.toLocaleString() ?? Math.round(budget.total / budget.days).toLocaleString()}`,
    14,
    y
  );
  y += 14;

  // Tips
  if (budget.tips?.length) {
    checkPageBreak(16);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEXT_DARK);
    doc.text("Money-Saving Tips", 14, y);
    y += 8;

    for (let i = 0; i < budget.tips.length; i++) {
      const tip = budget.tips[i];
      const tipLines = doc.splitTextToSize(`${i + 1}. ${tip}`, 178) as string[];
      checkPageBreak(tipLines.length * 5 + 4);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...TEXT_MUTED);
      doc.text(tipLines, 16, y);
      y += tipLines.length * 5 + 3;
    }
  }

  addFooter(doc, page);
  doc.save(`YatraSathi_Budget_${budget.destination.replace(/\s+/g, "_")}.pdf`);
};
