"""
YatraSathi ✈️ — Page 1: AI Trip Planner
Complete day-by-day itinerary generator powered by Google Gemini
"""

import streamlit as st
from utils.gemini_helper import get_gemini_response
from utils.constants import (
    INTERESTS,
    BUDGET_RANGES,
    TRAVEL_STYLES,
    FOOD_PREFERENCES,
    INDIAN_CITIES,
    INTERNATIONAL_CITIES,
)

from utils.styles import load_global_css, sidebar_branding
load_global_css()
sidebar_branding()

# ─────────────────────────────────────────────────────────────
#  Page CSS
# ─────────────────────────────────────────────────────────────
st.markdown(
    """
    <style>
    .tip-box {
        background: linear-gradient(135deg, rgba(255,140,0,0.12), rgba(255,75,75,0.12));
        border: 1px solid rgba(255,140,0,0.4);
        border-radius: 12px;
        padding: 14px 20px;
        font-size: 0.92rem;
        color: #ffd080;
        margin-bottom: 1.2rem;
    }
    .itinerary-box {
        background: #1a1a2e;
        border: 1px solid rgba(255,75,75,0.3);
        border-radius: 16px;
        padding: 28px 32px;
        margin-top: 0.5rem;
    }
    .feedback-box {
        background: #1e1e2e;
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 12px;
        padding: 16px 22px;
        margin-top: 1.5rem;
    }
    div[data-testid="stForm"] {
        background: #1a1a2e;
        border: 1px solid rgba(255,75,75,0.2);
        border-radius: 16px;
        padding: 24px 28px;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────────────────────
#  HEADER
# ─────────────────────────────────────────────────────────────
st.title("🤖 AI Trip Planner")
st.markdown(
    "*Get a complete day-by-day travel itinerary generated by AI in seconds.*"
)
st.divider()

# Tip box
st.markdown(
    '<div class="tip-box">'
    "💡 <b>Tip:</b> The more specific your inputs, the better your itinerary! "
    "Try adding special requirements like 'prefer morning departures' or 'need wheelchair access'."
    "</div>",
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────────────────────
#  Session state init
# ─────────────────────────────────────────────────────────────
DEFAULT = {
    "itinerary_text": None,
    "show_result":    False,
    "sample_filled":  False,
    # form field defaults
    "src":            "",
    "dst":            "",
    "days":           3,
    "travelers":      2,
    "budget":         "Standard",
    "style":          "Couple",
    "interests":      ["Beach & Water Sports", "Food & Cuisine", "Nightlife"],
    "food":           "No Preference",
    "accommodation":  "No Preference",
    "special":        "",
}
for k, v in DEFAULT.items():
    if k not in st.session_state:
        st.session_state[k] = v


def load_sample():
    """Pre-fill form with a sample Delhi → Goa trip."""
    st.session_state["src"]           = "Delhi"
    st.session_state["dst"]           = "Goa"
    st.session_state["days"]          = 4
    st.session_state["travelers"]     = 4
    st.session_state["budget"]        = "Standard"
    st.session_state["style"]         = "Friends Group"
    st.session_state["interests"]     = ["Beach & Water Sports", "Food & Cuisine", "Nightlife"]
    st.session_state["food"]          = "No Preference"
    st.session_state["accommodation"] = "Hostels"
    st.session_state["special"]       = "Budget-conscious, prefer lively areas"
    st.session_state["sample_filled"] = True


# Sample Trip button (outside the form so it can call callbacks freely)
sample_col, _ = st.columns([1, 3])
with sample_col:
    st.button("🎯 Load Sample Trip  (Delhi → Goa)", on_click=load_sample, use_container_width=True)

st.write("")

# ─────────────────────────────────────────────────────────────
#  INPUT FORM
# ─────────────────────────────────────────────────────────────
ACCOMMODATION_OPTIONS = [
    "No Preference", "Budget Hotels", "3-Star", "4-Star",
    "5-Star", "Hostels", "Homestays", "Resorts",
]

with st.form("trip_form", clear_on_submit=False):

    # Row 1 — Cities
    c1, c2 = st.columns(2)
    with c1:
        source = st.text_input(
            "🏠 Source City",
            value=st.session_state["src"],
            placeholder="e.g., Mumbai",
        )
    with c2:
        destination = st.text_input(
            "📍 Destination City",
            value=st.session_state["dst"],
            placeholder="e.g., Manali",
        )

    # Row 2 — Duration & Travellers
    c3, c4 = st.columns(2)
    with c3:
        num_days = st.number_input(
            "📅 Number of Days",
            min_value=1, max_value=30,
            value=st.session_state["days"],
            step=1,
        )
    with c4:
        num_travelers = st.number_input(
            "👥 Number of Travelers",
            min_value=1, max_value=20,
            value=st.session_state["travelers"],
            step=1,
        )

    # Row 3 — Budget & Travel Style
    c5, c6 = st.columns(2)
    budget_keys = list(BUDGET_RANGES.keys())
    with c5:
        budget_level = st.selectbox(
            "💰 Budget Level",
            options=budget_keys,
            index=budget_keys.index(st.session_state["budget"])
            if st.session_state["budget"] in budget_keys else 2,
            format_func=lambda k: f"{k}  —  {BUDGET_RANGES[k]}",
        )
    with c6:
        travel_style = st.selectbox(
            "🧳 Travel Style",
            options=TRAVEL_STYLES,
            index=TRAVEL_STYLES.index(st.session_state["style"])
            if st.session_state["style"] in TRAVEL_STYLES else 0,
        )

    # Row 4 — Interests
    selected_interests = st.multiselect(
        "🎯 Interests  (select at least one)",
        options=INTERESTS,
        default=[i for i in st.session_state["interests"] if i in INTERESTS],
    )

    # Row 5 — Food & Accommodation
    c7, c8 = st.columns(2)
    with c7:
        food_preference = st.selectbox(
            "🍽️ Food Preference",
            options=FOOD_PREFERENCES,
            index=FOOD_PREFERENCES.index(st.session_state["food"])
            if st.session_state["food"] in FOOD_PREFERENCES else 4,
        )
    with c8:
        accommodation = st.selectbox(
            "🏨 Accommodation Preference",
            options=ACCOMMODATION_OPTIONS,
            index=ACCOMMODATION_OPTIONS.index(st.session_state["accommodation"])
            if st.session_state["accommodation"] in ACCOMMODATION_OPTIONS else 0,
        )

    # Row 6 — Special Requirements
    special_requirements = st.text_area(
        "✏️ Special Requirements  (optional)",
        value=st.session_state["special"],
        placeholder=(
            "e.g., wheelchair accessible, pet-friendly, "
            "early morning flights preferred, vegetarian only restaurants..."
        ),
        height=90,
    )

    st.write("")
    submitted = st.form_submit_button(
        "🚀 Generate My Itinerary",
        use_container_width=True,
        type="primary",
    )


# ─────────────────────────────────────────────────────────────
#  BUILD PROMPT
# ─────────────────────────────────────────────────────────────
def build_prompt(src, dst, days, travelers, budget, style, interests, food, stay, special):
    interests_str = ", ".join(interests)
    special_str   = special.strip() if special.strip() else "None"
    return f"""You are "YatraSathi", an expert Indian travel planner AI.
Create a DETAILED {days}-day travel itinerary.

TRIP DETAILS:
- From: {src}
- To: {dst}
- Duration: {days} days
- Travelers: {travelers} ({style})
- Budget Level: {budget}  ({BUDGET_RANGES[budget]})
- Interests: {interests_str}
- Food Preference: {food}
- Stay Preference: {stay}
- Special Requirements: {special_str}

GENERATE THE FOLLOWING SECTIONS:

## 🚀 TRIP OVERVIEW
Brief exciting overview of this trip in 3-4 lines.

## 🛫 HOW TO REACH {dst} FROM {src}
- ✈️ By Flight: Available airlines, approx cost, duration
- 🚂 By Train: Best trains, approx cost, duration
- 🚗 By Road: Distance, route, toll info, duration
- (Include whichever modes are applicable)
- RECOMMEND the best option for their budget level

## 🚇 LOCAL TRANSPORT IN {dst}
⚠️ ACCURACY IS CRITICAL — Only list transport that genuinely exists and legally operates in {dst}:
- Clearly state if Ola/Uber/Rapido or other app-based cab aggregators are AVAILABLE or BANNED at {dst} (e.g., they are banned in Goa — only local taxis and the GoaMiles app operate there)
- Include Metro lines if {dst} has them: Delhi Metro, Namma Metro (Bengaluru), Hyderabad Metro, Chennai Metro, Kochi Metro, Kolkata Metro, Mumbai Metro, Jaipur Metro, etc.
- Include suburban/local trains if applicable: Mumbai Local, Chennai Suburban/MRTS, Kolkata Suburban Railway, etc.
- Include ferries/water transport if relevant (Goa river ferries, Kerala backwater boats, Andaman island ferries, Mumbai ferry)
- Mention city-specific apps or resources (e.g., GoaMiles for Goa, TS Metro App for Hyderabad, DMRC app for Delhi)
- Include auto-rickshaws, local buses, HOHO buses, cycle rickshaws — wherever actually used
- Give per-day transport budget estimate for {budget} tier travellers

## 📋 DAY-BY-DAY ITINERARY

For EACH day provide this EXACT format:

### 📅 Day X: [Theme of the Day]

**🌅 Morning (6 AM - 12 PM)**
- Activity 1 with specific place name and timing
- Activity 2 with specific place name and timing

**🌞 Afternoon (12 PM - 5 PM)**
- Lunch recommendation: [Specific restaurant/dhaba name] — [What to order] — [Approx cost per person]
- Activity with specific place name and timing

**🌆 Evening (5 PM - 9 PM)**
- Activity with specific place name and timing
- Dinner recommendation: [Specific restaurant name] — [What to order] — [Approx cost per person]

**🏨 Stay:** [Specific hotel/stay name] — [Approx cost/night]

**💰 Day Cost Estimate:** ₹X,XXX - ₹X,XXX per person

**💡 Pro Tip:** One useful tip for this day

---

## 🍽️ MUST-TRY LOCAL FOOD
List 5-7 local dishes/beverages specific to {dst} with where to try them.

## 🎒 PACKING CHECKLIST
10 essential items to pack for this specific trip.

## ⚠️ IMPORTANT TIPS & SAFETY
5 important tips including safety, scams to avoid, local customs, emergency numbers.

## 💰 TOTAL BUDGET SUMMARY
| Category | Min (₹) | Max (₹) |
|----------|---------|---------|
| Travel (to & fro) | | |
| Accommodation ({days} nights) | | |
| Food & Drinks | | |
| Activities & Entry Fees | | |
| Local Transport | | |
| Shopping & Misc | | |
| **TOTAL per person** | | |
| **TOTAL for {travelers} people** | | |

IMPORTANT RULES:
- Use ONLY real place names, real restaurant names, real hotel names
- All costs in Indian Rupees (₹)
- Be specific with timings
- Consider the budget level for all recommendations
- Consider food preference for all meal suggestions
- Make it practical and actionable
- If international destination, mention visa and currency info
- ⚠️ TRANSPORT ACCURACY: Never assume Ola/Uber/Rapido operate everywhere — they are banned in some places. Always specify the correct, legally-operating local transport modes for {dst}. Include local trains and metro if they exist in {dst}. For each day's movement, suggest the ACTUAL available transport in {dst}.
"""


# ─────────────────────────────────────────────────────────────
#  FORM SUBMISSION HANDLER
# ─────────────────────────────────────────────────────────────
if submitted:
    # -- Persist values in session state so they survive rerun --
    st.session_state["src"]           = source
    st.session_state["dst"]           = destination
    st.session_state["days"]          = int(num_days)
    st.session_state["travelers"]     = int(num_travelers)
    st.session_state["budget"]        = budget_level
    st.session_state["style"]         = travel_style
    st.session_state["interests"]     = selected_interests
    st.session_state["food"]          = food_preference
    st.session_state["accommodation"] = accommodation
    st.session_state["special"]       = special_requirements

    # -- Validation --
    errors = []
    if not source.strip():
        errors.append("⚠️ Please enter a **Source City**.")
    if not destination.strip():
        errors.append("⚠️ Please enter a **Destination City**.")
    if source.strip().lower() == destination.strip().lower() and source.strip():
        errors.append("⚠️ Source and Destination **cannot be the same city**.")
    if not selected_interests:
        errors.append("⚠️ Please select **at least one Interest**.")

    if errors:
        for e in errors:
            st.warning(e)
        st.stop()

    # -- Call Gemini --
    prompt = build_prompt(
        source.strip(), destination.strip(),
        int(num_days), int(num_travelers),
        budget_level, travel_style,
        selected_interests, food_preference,
        accommodation, special_requirements,
    )

    with st.spinner("🤖 AI is crafting your perfect itinerary… this takes 15-30 seconds"):
        result = get_gemini_response(prompt, temperature=0.75)

    if result is None:
        st.error(
            "😔 Oops! AI is taking a break. Please try again in a moment. "
            "If the problem persists, check your Gemini API key."
        )
        st.stop()

    st.session_state["itinerary_text"] = result
    st.session_state["show_result"]    = True

# ─────────────────────────────────────────────────────────────
#  RESULT DISPLAY
# ─────────────────────────────────────────────────────────────
if st.session_state["show_result"] and st.session_state["itinerary_text"]:
    itinerary = st.session_state["itinerary_text"]
    src_city  = st.session_state["src"]
    dst_city  = st.session_state["dst"]
    days_val  = st.session_state["days"]

    st.divider()
    st.success("✅ Itinerary generated successfully! Scroll down to explore your trip plan.")

    # Action buttons
    btn1, btn2, btn3 = st.columns(3, gap="medium")

    filename = f"YatraSathi_{src_city}_to_{dst_city}_{days_val}days.txt"
    with btn1:
        st.download_button(
            label="📥 Download as Text",
            data=itinerary,
            file_name=filename,
            mime="text/plain",
            use_container_width=True,
        )
    with btn2:
        if st.button("🔄 Regenerate", use_container_width=True):
            st.session_state["itinerary_text"] = None
            st.session_state["show_result"]    = False
            st.rerun()
    with btn3:
        show_raw = st.button("📋 View Raw Text", use_container_width=True)

    st.write("")

    # Itinerary body
    st.markdown('<div class="itinerary-box">', unsafe_allow_html=True)
    st.markdown(itinerary)
    st.markdown("</div>", unsafe_allow_html=True)

    # Raw copy view (toggle)
    if show_raw:
        st.divider()
        st.markdown("##### 📋 Raw Text — select all & copy")
        st.code(itinerary, language="markdown")

    # Feedback
    st.divider()
    st.markdown('<div class="feedback-box">', unsafe_allow_html=True)
    st.markdown("#### 💬 How was this itinerary?")
    col_r, col_s = st.columns([3, 1])
    with col_r:
        st.radio(
            label="rating",
            options=["🤩 Amazing", "😊 Good", "😐 Average", "😞 Poor"],
            horizontal=True,
            label_visibility="collapsed",
        )
    with col_s:
        st.button("Submit Feedback", use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    # Footer tip
    st.write("")
    st.caption(
        f"✈️ **{src_city} → {dst_city}** | {days_val} days | "
        f"{st.session_state['travelers']} traveller(s) | "
        f"Budget: {st.session_state['budget']} | "
        "Powered by Google Gemini"
    )
