# ============================================================
#  YatraSathi — PDF Generator (FPDF2-based)
# ============================================================
# Requirements: pip install fpdf2

from __future__ import annotations

import io
import re
import textwrap
import unicodedata
from datetime import datetime

import streamlit as st

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


# ─────────────────────────────────────────────────────────────
#  Unicode / Emoji cleaner
# ─────────────────────────────────────────────────────────────

# Map common travel-related symbols to ASCII equivalents
_SYMBOL_MAP: dict[str, str] = {
    # Currency
    "₹": "Rs.", "€": "EUR", "£": "GBP", "$": "USD", "¥": "JPY",
    # Arrows / bullets
    "→": "->", "←": "<-", "↑": "^", "↓": "v", "•": "-", "·": "-",
    "–": "-", "—": "--", "\u2019": "'", "\u2018": "'",
    "\u201c": '"', "\u201d": '"',
    # Misc symbols
    "★": "*", "☆": "*", "✓": "OK", "✔": "OK", "✗": "X", "✘": "X",
    "©": "(c)", "®": "(R)", "™": "(TM)", "°": " deg",
    "½": "1/2", "¼": "1/4", "¾": "3/4",
    # Common emoji text equivalents (just in case they sneak through)
    "\u2708": "[Plane]",    # ✈
    "\u2764": "[Heart]",    # ❤
    "\u2605": "[Star]",     # ★
}

# Regex: any character outside Latin-1 printable that isn't in our map
_NON_LATIN1 = re.compile(r"[^\x20-\x7E\x80-\xFF]")


def clean_text_for_pdf(text: str) -> str:
    """
    Sanitise *text* so FPDF (Helvetica/Latin-1) can render it safely.

    Steps:
      1. Replace known symbols with ASCII equivalents.
      2. Strip emoji and other characters outside the Latin-1 printable range.
      3. Collapse any resulting runs of whitespace.

    Always returns a plain string — never raises.
    """
    if not text:
        return ""

    try:
        # Step 1 — known symbol replacements
        for char, replacement in _SYMBOL_MAP.items():
            text = text.replace(char, replacement)

        # Step 2 — normalise to NFC, then strip non-Latin-1 printable chars
        text = unicodedata.normalize("NFC", text)
        text = _NON_LATIN1.sub("", text)

        # Step 3 — collapse multiple spaces (but preserve newlines)
        lines = text.split("\n")
        lines = [re.sub(r"[ \t]+", " ", ln).rstrip() for ln in lines]
        return "\n".join(lines)

    except Exception:
        # Last-resort: encode to ASCII, replacing everything unknown
        return text.encode("ascii", errors="replace").decode("ascii")


# ─────────────────────────────────────────────────────────────
#  Core PDF class
# ─────────────────────────────────────────────────────────────
class YatraSathiPDF(FPDF):
    """Custom FPDF subclass with branded header & footer."""

    # Subtitle printed just below the logo line
    _subtitle: str = ""

    def header(self):
        # Logo / brand
        self.set_font("Helvetica", "B", 17)
        self.set_text_color(220, 50, 50)
        self.cell(140, 10, "YatraSathi  AI Travel Planner", align="L")
        # Date (top-right)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, datetime.now().strftime("%d %b %Y"), align="R",
                  new_x="LMARGIN", new_y="NEXT")
        # Optional subtitle row
        if self._subtitle:
            self.set_font("Helvetica", "I", 9)
            self.set_text_color(100, 100, 100)
            self.cell(0, 5, clean_text_for_pdf(self._subtitle),
                      new_x="LMARGIN", new_y="NEXT")
        # Divider line
        self.set_draw_color(220, 50, 50)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        date_str = datetime.now().strftime("%d %b %Y")
        self.cell(
            0, 10,
            f"Page {self.page_no()} | Generated by YatraSathi - AI Travel Planner | {date_str}",
            align="C",
        )

# ─────────────────────────────────────────────────────────────
#  Internal: render markdown-style content onto a PDF page
# ─────────────────────────────────────────────────────────────
def _render_content(pdf: YatraSathiPDF, content: str) -> None:
    """
    Walk through *content* line-by-line and apply basic Markdown
    heading / bullet formatting using only Helvetica (Latin-1 safe).
    """
    for raw_line in content.split("\n"):
        line = clean_text_for_pdf(raw_line).strip()

        if not line:
            pdf.ln(2)
            continue

        # H1 — "# text"  or  "## text"
        if line.startswith("### "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(200, 40, 40)
            pdf.multi_cell(0, 6, line[4:])
            pdf.set_text_color(30, 30, 30)

        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(200, 40, 40)
            pdf.multi_cell(0, 7, line[3:])
            pdf.set_text_color(30, 30, 30)

        elif line.startswith("# "):
            pdf.set_font("Helvetica", "B", 15)
            pdf.set_text_color(200, 40, 40)
            pdf.multi_cell(0, 8, line[2:])
            pdf.set_text_color(30, 30, 30)

        # Horizontal rule "---" or "==="
        elif re.match(r"^[-=]{3,}$", line):
            pdf.set_draw_color(180, 180, 180)
            pdf.set_line_width(0.3)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)

        # Bullet points "- " or "* "
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            # indent + bullet character
            pdf.set_x(14)
            pdf.multi_cell(0, 5, f"- {line[2:]}")

        # Bold-only line "**text**"
        elif line.startswith("**") and line.endswith("**") and len(line) > 4:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, line.strip("*"))

        # Table rows (pipe-delimited) — render as plain text
        elif "|" in line:
            pdf.set_font("Courier", "", 8)
            pdf.set_text_color(50, 50, 50)
            # strip leading / trailing pipes
            row = line.strip("|").replace("|", "  |  ")
            pdf.multi_cell(0, 5, row)
            pdf.set_font("Helvetica", "", 10)

        # Default body text
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 5, line)


# ─────────────────────────────────────────────────────────────
#  Public API — primary function requested
# ─────────────────────────────────────────────────────────────
def generate_pdf(
    title: str,
    content: str,
    filename: str = "YatraSathi_Report.pdf",
) -> bytes | None:
    """
    Generate a PDF report and return it as raw bytes.

    Parameters
    ----------
    title    : Page subtitle printed just below the YatraSathi logo.
               E.g. "YatraSathi Travel Itinerary — Goa | 4 Days"
    content  : The body text / AI-generated itinerary (Markdown-ish).
               Unicode, emojis, and ₹ symbols are handled automatically.
    filename : Suggested download filename (not used internally, kept for
               API symmetry with st.download_button callers).

    Returns
    -------
    bytes
        Raw PDF bytes ready for ``st.download_button(data=...)``.
    None
        If fpdf2 is not installed.
    """
    if not FPDF_AVAILABLE:
        st.warning(
            "📦 PDF export requires **fpdf2**. "
            "Install it with `.venv\\\\Scripts\\\\pip install fpdf2`."
        )
        return None

    try:
        pdf = YatraSathiPDF(orientation="P", unit="mm", format="A4")
        pdf._subtitle = clean_text_for_pdf(title)
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.set_margins(left=12, top=12, right=12)
        pdf.add_page()

        # ── Title block ─────────────────────────────────────
        clean_title = clean_text_for_pdf(title)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 8, clean_title)
        pdf.ln(3)

        # Thin accent line under title
        pdf.set_draw_color(220, 50, 50)
        pdf.set_line_width(0.4)
        pdf.line(12, pdf.get_y(), 198, pdf.get_y())
        pdf.ln(5)

        # ── Body content ────────────────────────────────────
        _render_content(pdf, content)

        # ── Flush to bytes ──────────────────────────────────
        buf = io.BytesIO()
        pdf.output(buf)
        return buf.getvalue()

    except Exception as exc:
        # Never crash — return None so callers can show a fallback
        st.warning(f"⚠️ PDF generation error: {exc}")
        return None


# ─────────────────────────────────────────────────────────────
#  Backward-compatible function (used by Page 1)
# ─────────────────────────────────────────────────────────────
def generate_itinerary_pdf(
    destination: str,
    duration: str,
    travel_style: str,
    budget: str,
    itinerary_text: str,
) -> bytes | None:
    """
    Convenience wrapper around generate_pdf() for itinerary pages.
    Kept for backward compatibility with Page 1 (AI Trip Planner).
    """
    title = (
        f"YatraSathi Travel Itinerary  |  {destination}  |  "
        f"{duration}  |  {travel_style}  |  {budget}"
    )
    return generate_pdf(title=title, content=itinerary_text)


# ─────────────────────────────────────────────────────────────
#  Streamlit convenience wrapper
# ─────────────────────────────────────────────────────────────
def pdf_download_button(
    label: str,
    pdf_bytes: bytes,
    filename: str = "YatraSathi_Itinerary.pdf",
) -> None:
    """Render an ``st.download_button`` for a PDF bytes object."""
    st.download_button(
        label=label,
        data=pdf_bytes,
        file_name=filename,
        mime="application/pdf",
        use_container_width=True,
    )
